apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-separation-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-separation-service
  template:
    metadata:
      name: orders-separation-service
      labels:
        app: orders-separation-service
    spec:
      containers:
        - name: orders-separation-service
          resources:
            requests:
              cpu: 300m
              memory: 600Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
          image: {{ .Values.images.ordersseparationservice }}
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: orders-separation-service-svc
spec:
  ports:
    - port: 8091
      targetPort: 8091
  selector:
    app: orders-separation-service
  type: ClusterIP