package com.example.deliveryservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Deliveries")
public class Delivery {

    String id;

    String orderId;

    String product;

    String customerName;

    String destination;

    DeliveryStatus status;

    LocalDateTime deliveredAt;

    LocalDateTime createdAt;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getOrderId() {
        return orderId;
    }

    @DynamoDBAttribute
    public String getProduct() {
        return product;
    }

    @DynamoDBAttribute
    public String getCustomerName() {
        return customerName;
    }

    @DynamoDBAttribute
    public String getDestination() {
        return destination;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    public DeliveryStatus getStatus() {
        return status;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getDeliveredAt() {
        return deliveredAt;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {
        @Override
        public String convert( final LocalDateTime time ) {
            return time.toString();
        }
        @Override
        public LocalDateTime unconvert( final String stringValue ) {

            return LocalDateTime.parse(stringValue);
        }
    }
}
