server:
  port: 8091
spring:
  kafka:
    bootstrap-servers: 'localhost:9092,localhost:9093,localhost:9094'
    streams:
      application-id: "orders-separation-service"
    properties:
      schema:
        registry:
          url: "http://localhost:8081"

topic-names:
  order-creation: order-creation
  cheap-order-creation: cheap-order-creation
  expensive-order-creation: expensive-order-creation
