server:
  port: 8090
spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESSKEY}
        secret-key: ${AWS_SECRETKEY}
      region:
        static: eu-north-1
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/delivery-service-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

queues:
  order-creation-delivery:
    name: OrderCreationDeliveryQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderCreationDeliveryQueue
  order-creation-reports:
    name: OrderCreationReportsQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderCreationReportsQueue
  order-update-status:
    name: OrderUpdateStatusQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderUpdateStatusQueue
