server:
  port: 8090
spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESSKEY}
        secret-key: ${AWS_SECRETKEY}
      region:
        static: eu-north-1

amazon:
  aws:
    accesskey: ${AWS_ACCESSKEY}
    secretkey: ${AWS_SECRETKEY}
  dynamodb:
    endpoint: dynamodb.eu-north-1.amazonaws.com


queues:
  order-creation-delivery:
    name: OrderCreationDeliveryQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderCreationDeliveryQueue
  order-creation-reports:
    name: OrderCreationReportsQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderCreationReportsQueue
  order-update-status:
    name: OrderUpdateStatusQueue
    url: https://sqs.eu-north-1.amazonaws.com/465248673675/OrderUpdateStatusQueue
